# Generated by Django 5.2.6 on 2025-09-25 23:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('vacuna', 'Vacuna'), ('procedimiento', 'Procedimiento')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='abierta', max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='vetbio.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetbio.atencion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetbio.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='vetbio.tutor'),
        ),
    ]
